 const ActionTypes = {
    CURRENTUSER:'CURRENTUSER',
    MYCLINICS:'MYCLINICS',
    DATA:'DATA',
    LOADER:'LOADER',
    SHOWERROR: 'SHOWERROR',
    MYDOCTORS: 'MYDOCTORS',
    HIDEERROR: 'HIDEERROR',
}

export default ActionTypes;
