export default (
    [
        {abbr: "AF", country: "Afghanistan", label: "Afghanistan"},
    {abbr: "AL", country: "Albania", label: "Albania"},
    {abbr: "DZ", country: "Algeria", label: "Algeria"},
    {abbr: "AS", country: "American Samoa", label: "American Samoa"},
    {abbr: "AD", country: "Andorra", label: "Andorra"},
    {abbr: "AO", country: "Angola", label: "Angola"},
    {abbr: "AI", country: "Anguilla", label: "Anguilla"},
    {abbr: "AG", country: "Antigua and Barbuda", label: "Antigua and Barbuda"},
    {abbr: "AR", country: "Argentina", label: "Argentina"},
    {abbr: "AM", country: "Armenia", label: "Armenia"},
    {abbr: "AW", country: "Aruba", label: "Aruba"},
    {abbr: "AU", country: "Australia", label: "Australia"},
    {abbr: "AT", country: "Austria", label: "Austria"},
    {abbr: "AZ", country: "Azerbaijan", label: "Azerbaijan"},
    {abbr: "BS", country: "Bahamas", label: "Bahamas"},
    {abbr: "BD", country: "Bangladesh", label: "Bangladesh"},
    {abbr: "BB", country: "Barbados", label: "Barbados"},
    {abbr: "BY", country: "Belarus", label: "Belarus"},
    {abbr: "BE", country: "Belgium", label: "Belgium"},
    {abbr: "BZ", country: "Belize", label: "Belize"},
    {abbr: "BJ", country: "Benin", label: "Benin"},
    {abbr: "BM", country: "Bermuda", label: "Bermuda"},
    {abbr: "BT", country: "Bhutan", label: "Bhutan"},
    {abbr: "BO", country: "Bolivia, Plurinational State of", label: "Bolivia, Plurinational State of"},
    {abbr: "BA", country: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina"},
    {abbr: "BW", country: "Botswana", label: "Botswana"},
    {abbr: "BR", country: "Brazil", label: "Brazil"},
    {abbr: "IO", country: "British Indian Ocean Territory", label: "British Indian Ocean Territory"},
    {abbr: "BG", country: "Bulgaria", label: "Bulgaria"},
    {abbr: "BF", country: "Burkina Faso", label: "Burkina Faso"},
    {abbr: "BI", country: "Burundi", label: "Burundi"},
    {abbr: "KH", country: "Cambodia", label: "Cambodia"},
    {abbr: "CM", country: "Cameroon", label: "Cameroon"},
    {abbr: "CA", country: "Canada", label: "Canada"},
    {abbr: "CV", country: "Cape Verde", label: "Cape Verde"},
    {abbr: "KY", country: "Cayman Islands", label: "Cayman Islands"},
    {abbr: "CF", country: "Central African Republic", label: "Central African Republic"},
    {abbr: "TD", country: "Chad", label: "Chad"},
    {abbr: "CL", country: "Chile", label: "Chile"},
    {abbr: "CN", country: "China", label: "China"},
    {abbr: "CO", country: "Colombia", label: "Colombia"},
    {abbr: "KM", country: "Comoros", label: "Comoros"},
    {abbr: "CG", country: "Congo", label: "Congo"},
    {abbr: "CD", country: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo"},
    {abbr: "CK", country: "Cook Islands", label: "Cook Islands"},
    {abbr: "CR", country: "Costa Rica", label: "Costa Rica"},
    {abbr: "CI", country: "Côte d'Ivoire", label: "Côte d'Ivoire"},
    {abbr: "HR", country: "Croatia", label: "Croatia"},
    {abbr: "CU", country: "Cuba", label: "Cuba"},
    {abbr: "CW", country: "Curaçao", label: "Curaçao"},
    {abbr: "CY", country: "Cyprus", label: "Cyprus"},
    {abbr: "CZ", country: "Czech Republic", label: "Czech Republic"},
    {abbr: "DK", country: "Denmark", label: "Denmark"},
    {abbr: "DJ", country: "Djibouti", label: "Djibouti"},
    {abbr: "DM", country: "Dominica", label: "Dominica"},
    {abbr: "DO", country: "Dominican Republic", label: "Dominican Republic"},
    {abbr: "EC", country: "Ecuador", label: "Ecuador"},
    {abbr: "EG", country: "Egypt", label: "Egypt"},
    {abbr: "SV", country: "El Salvador", label: "El Salvador"},
    {abbr: "GQ", country: "Equatorial Guinea", label: "Equatorial Guinea"},
    {abbr: "ER", country: "Eritrea", label: "Eritrea"},
    {abbr: "EE", country: "Estonia", label: "Estonia"},
    {abbr: "ET", country: "Ethiopia", label: "Ethiopia"},
    {abbr: "FK", country: "Falkland Islands (Malvinas)", label: "Falkland Islands (Malvinas)"},
    {abbr: "FO", country: "Faroe Islands", label: "Faroe Islands"},
    {abbr: "FJ", country: "Fiji", label: "Fiji"},
    {abbr: "FI", country: "Finland", label: "Finland"},
    {abbr: "FR", country: "France", label: "France"},
    {abbr: "PF", country: "French Polynesia", label: "French Polynesia"},
    {abbr: "GA", country: "Gabon", label: "Gabon"},
    {abbr: "GM", country: "Gambia", label: "Gambia"},
    {abbr: "GE", country: "Georgia", label: "Georgia"},
    {abbr: "DE", country: "Germany", label: "Germany"},
    {abbr: "GH", country: "Ghana", label: "Ghana"},
    {abbr: "GI", country: "Gibraltar", label: "Gibraltar"},
    {abbr: "GR", country: "Greece", label: "Greece"},
    {abbr: "GL", country: "Greenland", label: "Greenland"},
    {abbr: "GD", country: "Grenada", label: "Grenada"},
    {abbr: "GU", country: "Guam", label: "Guam"},
    {abbr: "GT", country: "Guatemala", label: "Guatemala"},
    {abbr: "GG", country: "Guernsey", label: "Guernsey"},
    {abbr: "GN", country: "Guinea", label: "Guinea"},
    {abbr: "GW", country: "Guinea-Bissau", label: "Guinea-Bissau"},
    {abbr: "HT", country: "Haiti", label: "Haiti"},
    {abbr: "HN", country: "Honduras", label: "Honduras"},
    {abbr: "HK", country: "Hong Kong", label: "Hong Kong"},
    {abbr: "HU", country: "Hungary", label: "Hungary"},
    {abbr: "IS", country: "Iceland", label: "Iceland"},
    {abbr: "IN", country: "India", label: "India"},
    {abbr: "ID", country: "Indonesia", label: "Indonesia"},
    {abbr: "IR", country: "Iran, Islamic Republic of", label: "Iran, Islamic Republic of"},
    {abbr: "IQ", country: "Iraq", label: "Iraq"},
    {abbr: "IE", country: "Ireland", label: "Ireland"},
    {abbr: "IM", country: "Isle of Man", label: "Isle of Man"},
    {abbr: "IL", country: "Israel", label: "Israel"},
    {abbr: "IT", country: "Italy", label: "Italy"},
    {abbr: "JM", country: "Jamaica", label: "Jamaica"},
    {abbr: "JP", country: "Japan", label: "Japan"},
    {abbr: "JE", country: "Jersey", label: "Jersey"},
    {abbr: "JO", country: "Jordan", label: "Jordan"},
    
    {abbr: "KZ", country: "Kazakhstan", label: "Kazakhstan"},
    {abbr: "KE", country: "Kenya", label: "Kenya"},
    {abbr: "KI", country: "Kiribati", label: "Kiribati"},
    {abbr: "KP", country: "North Korea", label: "North Korea"},
    {abbr: "KR", country: "South Korea", label: "South Korea"},
    {abbr: "KW", country: "Kuwait", label: "Kuwait"},
    {abbr: "KG", country: "Kyrgyzstan", label: "Kyrgyzstan"},
    {abbr: "LA", country: "Lao People's Democratic Republic", label: "Lao People's Democratic Republic"},
    {abbr: "LV", country: "Latvia", label: "Latvia"},
    {abbr: "LB", country: "Lebanon", label: "Lebanon"},
    {abbr: "LS", country: "Lesotho", label: "Lesotho"},
    {abbr: "LR", country: "Liberia", label: "Liberia"},
    {abbr: "LY", country: "Libya", label: "Libya"},
    {abbr: "LI", country: "Liechtenstein", label: "Liechtenstein"},
    {abbr: "LT", country: "Lithuania", label: "Lithuania"},
    {abbr: "LU", country: "Luxembourg", label: "Luxembourg"},
    {abbr: "MO", country: "Macao", label: "Macao"},
    {abbr: "MK", country: "Republic of Macedonia", label: "Republic of Macedonia"},
    {abbr: "MG", country: "Madagascar", label: "Madagascar"},
    {abbr: "MW", country: "Malawi", label: "Malawi"},
    {abbr: "MY", country: "Malaysia", label: "Malaysia"},
    {abbr: "MV", country: "Maldives", label: "Maldives"},
    {abbr: "ML", country: "Mali", label: "Mali"},
    {abbr: "MT", country: "Malta", label: "Malta"},
    {abbr: "MH", country: "Marshall Islands", label: "Marshall Islands"},
    {abbr: "MQ", country: "Martinique", label: "Martinique"},
    {abbr: "MR", country: "Mauritania", label: "Mauritania"},
    {abbr: "MU", country: "Mauritius", label: "Mauritius"},
    {abbr: "MX", country: "Mexico", label: "Mexico"},
    {abbr: "FM", country: "Micronesia, Federated States of", label: "Micronesia, Federated States of"},
    {abbr: "MD", country: "Republic of Moldova", label: "Republic of Moldova"},
    {abbr: "MC", country: "Monaco", label: "Monaco"},
    {abbr: "MN", country: "Mongolia", label: "Mongolia"},
    {abbr: "ME", country: "Montenegro", label: "Montenegro"},
    {abbr: "MS", country: "Montserrat", label: "Montserrat"},
    {abbr: "MA", country: "Morocco", label: "Morocco"},
    {abbr: "MZ", country: "Mozambique", label: "Mozambique"},
    {abbr: "MM", country: "Myanmar", label: "Myanmar"},
    {abbr: "NA", country: "Namibia", label: "Namibia"},
    {abbr: "NR", country: "Nauru", label: "Nauru"},
    {abbr: "NP", country: "Nepal", label: "Nepal"},
    {abbr: "NL", country: "Netherlands", label: "Netherlands"},
    {abbr: "NZ", country: "New Zealand", label: "New Zealand"},
    {abbr: "NI", country: "Nicaragua", label: "Nicaragua"},
    {abbr: "NE", country: "Niger", label: "Niger"},
    {abbr: "NG", country: "Nigeria", label: "Nigeria"},
    {abbr: "NU", country: "Niue", label: "Niue"},
    {abbr: "NF", country: "Norfolk Island", label: "Norfolk Island"},
    {abbr: "MP", country: "Northern Mariana Islands", label: "Northern Mariana Islands"},
    {abbr: "NO", country: "Norway", label: "Norway"},
    {abbr: "OM", country: "Oman", label: "Oman"},
    {abbr: "PK", country: "Pakistan", label: "Pakistan"},
    {abbr: "PW", country: "Palau", label: "Palau"},
    {abbr: "PS", country: "Palestinian Territory", label: "Palestinian Territory"},
    {abbr: "PA", country: "Panama", label: "Panama"},
    {abbr: "PG", country: "Papua New Guinea", label: "Papua New Guinea"},
    {abbr: "PY", country: "Paraguay", label: "Paraguay"},
    {abbr: "PE", country: "Peru", label: "Peru"},
    {abbr: "PH", country: "Philippines", label: "Philippines"},
    {abbr: "PN", country: "Pitcairn", label: "Pitcairn"},
    {abbr: "PL", country: "Poland", label: "Poland"},
    {abbr: "PT", country: "Portugal", label: "Portugal"},
    {abbr: "PR", country: "Puerto Rico", label: "Puerto Rico"},
    {abbr: "QA", country: "Qatar", label: "Qatar"},
    {abbr: "RO", country: "Romania", label: "Romania"},
    {abbr: "RU", country: "Russian", label: "Russian"},
    {abbr: "RW", country: "Rwanda", label: "Rwanda"},
    {abbr: "KN", country: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis"},
    {abbr: "WS", country: "Samoa", label: "Samoa"},
    {abbr: "SM", country: "San Marino", label: "San Marino"},
    {abbr: "ST", country: "Sao Tome and Principe", label: "Sao Tome and Principe"},
    {abbr: "SA", country: "Saudi Arabia", label: "Saudi Arabia"},
    {abbr: "SN", country: "Senegal", label: "Senegal"},
    {abbr: "RS", country: "Serbia", label: "Serbia"},
    {abbr: "SC", country: "Seychelles", label: "Seychelles"},
    {abbr: "SL", country: "Sierra Leone", label: "Sierra Leone"},
    {abbr: "SG", country: "Singapore", label: "Singapore"},
    {abbr: "SX", country: "Sint Maarten", label: "Sint Maarten"},
    {abbr: "SK", country: "Slovakia", label: "Slovakia"},
    {abbr: "SI", country: "Slovenia", label: "Slovenia"},
    {abbr: "SB", country: "Solomon Islands", label: "Solomon Islands"},
    {abbr: "SO", country: "Somalia", label: "Somalia"},
    {abbr: "ZA", country: "South Africa", label: "South Africa"},
    {abbr: "SS", country: "South Sudan", label: "South Sudan"},
    {abbr: "ES", country: "Spain", label: "Spain"},
    {abbr: "LK", country: "Sri Lanka", label: "Sri Lanka"},
    {abbr: "SD", country: "Sudan", label: "Sudan"},
    {abbr: "SR", country: "Suriname", label: "Suriname"},
    {abbr: "SZ", country: "Swaziland", label: "Swaziland"},
    {abbr: "SE", country: "Sweden", label: "Sweden"},
    {abbr: "CH", country: "Switzerland", label: "Switzerland"},
    {abbr: "SY", country: "Syria", label: "Syria"},
    {abbr: "TW", country: "Taiwan, Province of China", label: "Taiwan, Province of China"},
    {abbr: "TJ", country: "Tajikistan", label: "Tajikistan"},
    {abbr: "TZ", country: "Tanzania", label: "Tanzania"},
    {abbr: "TH", country: "Thailand", label: "Thailand"},
    {abbr: "TG", country: "Togo", label: "Togo"},
    {abbr: "TK", country: "Tokelau", label: "Tokelau"},
    {abbr: "TO", country: "Tonga", label: "Tonga"},
    {abbr: "TT", country: "Trinidad and Tobago", label: "Trinidad and Tobago"},
    
    {abbr: "TN", country: "Tunisia", label: "Tunisia"},
    {abbr: "TR", country: "Turkey", label: "Turkey"},
    {abbr: "TM", country: "Turkmenistan", label: "Turkmenistan"},
    {abbr: "TC", country: "Turks and Caicos Islands", label: "Turks and Caicos Islands"},
    {abbr: "TV", country: "Tuvalu", label: "Tuvalu"},
    {abbr: "UG", country: "Uganda", label: "Uganda"},
    {abbr: "UA", country: "Ukraine", label: "Ukraine"},
    {abbr: "AE", country: "United Arab Emirates", label: "United Arab Emirates"},
    {abbr: "GB", country: "United Kingdom", label: "United Kingdom"},
    {abbr: "US", country: "United States", label: "United States"},
    {abbr: "UY", country: "Uruguay", label: "Uruguay"},
    {abbr: "UZ", country: "Uzbekistan", label: "Uzbekistan"},
    {abbr: "VU", country: "Vanuatu", label: "Vanuatu"},
    {abbr: "VE", country: "Venezuela, Bolivarian Republic of", label: "Venezuela, Bolivarian Republic of"},
    {abbr: "VN", country: "Viet Nam", label: "Viet Nam"},
    {abbr: "VI", country: "Virgin Islands", label: "Virgin Islands"},
    {abbr: "YE", country: "Yemen", label: "Yemen"},
    {abbr: "ZM", country: "Zambia", label: "Zambia"},
    {abbr: "ZW", country: "Zimbabwe", label: "Zimbabwe"},
    
    ]
);

